require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CapacitesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Capacite. As you add validations to Capacite, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CapacitesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all capacites as @capacites" do
      capacite = Capacite.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:capacites)).to eq([capacite])
    end
  end

  describe "GET show" do
    it "assigns the requested capacite as @capacite" do
      capacite = Capacite.create! valid_attributes
      get :show, {:id => capacite.to_param}, valid_session
      expect(assigns(:capacite)).to eq(capacite)
    end
  end

  describe "GET new" do
    it "assigns a new capacite as @capacite" do
      get :new, {}, valid_session
      expect(assigns(:capacite)).to be_a_new(Capacite)
    end
  end

  describe "GET edit" do
    it "assigns the requested capacite as @capacite" do
      capacite = Capacite.create! valid_attributes
      get :edit, {:id => capacite.to_param}, valid_session
      expect(assigns(:capacite)).to eq(capacite)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Capacite" do
        expect {
          post :create, {:capacite => valid_attributes}, valid_session
        }.to change(Capacite, :count).by(1)
      end

      it "assigns a newly created capacite as @capacite" do
        post :create, {:capacite => valid_attributes}, valid_session
        expect(assigns(:capacite)).to be_a(Capacite)
        expect(assigns(:capacite)).to be_persisted
      end

      it "redirects to the created capacite" do
        post :create, {:capacite => valid_attributes}, valid_session
        expect(response).to redirect_to(Capacite.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved capacite as @capacite" do
        post :create, {:capacite => invalid_attributes}, valid_session
        expect(assigns(:capacite)).to be_a_new(Capacite)
      end

      it "re-renders the 'new' template" do
        post :create, {:capacite => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested capacite" do
        capacite = Capacite.create! valid_attributes
        put :update, {:id => capacite.to_param, :capacite => new_attributes}, valid_session
        capacite.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested capacite as @capacite" do
        capacite = Capacite.create! valid_attributes
        put :update, {:id => capacite.to_param, :capacite => valid_attributes}, valid_session
        expect(assigns(:capacite)).to eq(capacite)
      end

      it "redirects to the capacite" do
        capacite = Capacite.create! valid_attributes
        put :update, {:id => capacite.to_param, :capacite => valid_attributes}, valid_session
        expect(response).to redirect_to(capacite)
      end
    end

    describe "with invalid params" do
      it "assigns the capacite as @capacite" do
        capacite = Capacite.create! valid_attributes
        put :update, {:id => capacite.to_param, :capacite => invalid_attributes}, valid_session
        expect(assigns(:capacite)).to eq(capacite)
      end

      it "re-renders the 'edit' template" do
        capacite = Capacite.create! valid_attributes
        put :update, {:id => capacite.to_param, :capacite => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested capacite" do
      capacite = Capacite.create! valid_attributes
      expect {
        delete :destroy, {:id => capacite.to_param}, valid_session
      }.to change(Capacite, :count).by(-1)
    end

    it "redirects to the capacites list" do
      capacite = Capacite.create! valid_attributes
      delete :destroy, {:id => capacite.to_param}, valid_session
      expect(response).to redirect_to(capacites_url)
    end
  end

end
