require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PartiesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Partie. As you add validations to Partie, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PartiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all parties as @parties" do
      partie = Partie.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:parties)).to eq([partie])
    end
  end

  describe "GET #show" do
    it "assigns the requested partie as @partie" do
      partie = Partie.create! valid_attributes
      get :show, {:id => partie.to_param}, valid_session
      expect(assigns(:partie)).to eq(partie)
    end
  end

  describe "GET #new" do
    it "assigns a new partie as @partie" do
      get :new, {}, valid_session
      expect(assigns(:partie)).to be_a_new(Partie)
    end
  end

  describe "GET #edit" do
    it "assigns the requested partie as @partie" do
      partie = Partie.create! valid_attributes
      get :edit, {:id => partie.to_param}, valid_session
      expect(assigns(:partie)).to eq(partie)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Partie" do
        expect {
          post :create, {:partie => valid_attributes}, valid_session
        }.to change(Partie, :count).by(1)
      end

      it "assigns a newly created partie as @partie" do
        post :create, {:partie => valid_attributes}, valid_session
        expect(assigns(:partie)).to be_a(Partie)
        expect(assigns(:partie)).to be_persisted
      end

      it "redirects to the created partie" do
        post :create, {:partie => valid_attributes}, valid_session
        expect(response).to redirect_to(Partie.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved partie as @partie" do
        post :create, {:partie => invalid_attributes}, valid_session
        expect(assigns(:partie)).to be_a_new(Partie)
      end

      it "re-renders the 'new' template" do
        post :create, {:partie => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested partie" do
        partie = Partie.create! valid_attributes
        put :update, {:id => partie.to_param, :partie => new_attributes}, valid_session
        partie.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested partie as @partie" do
        partie = Partie.create! valid_attributes
        put :update, {:id => partie.to_param, :partie => valid_attributes}, valid_session
        expect(assigns(:partie)).to eq(partie)
      end

      it "redirects to the partie" do
        partie = Partie.create! valid_attributes
        put :update, {:id => partie.to_param, :partie => valid_attributes}, valid_session
        expect(response).to redirect_to(partie)
      end
    end

    context "with invalid params" do
      it "assigns the partie as @partie" do
        partie = Partie.create! valid_attributes
        put :update, {:id => partie.to_param, :partie => invalid_attributes}, valid_session
        expect(assigns(:partie)).to eq(partie)
      end

      it "re-renders the 'edit' template" do
        partie = Partie.create! valid_attributes
        put :update, {:id => partie.to_param, :partie => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested partie" do
      partie = Partie.create! valid_attributes
      expect {
        delete :destroy, {:id => partie.to_param}, valid_session
      }.to change(Partie, :count).by(-1)
    end

    it "redirects to the parties list" do
      partie = Partie.create! valid_attributes
      delete :destroy, {:id => partie.to_param}, valid_session
      expect(response).to redirect_to(parties_url)
    end
  end

end
